// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOFe27_TiLicMM7JvqebNt5KSKX0AVo7A',
    appId: '1:719925176067:web:20f839466dbaf3334b2b36',
    messagingSenderId: '719925176067',
    projectId: 'notificationtest-d8ce3',
    authDomain: 'notificationtest-d8ce3.firebaseapp.com',
    storageBucket: 'notificationtest-d8ce3.appspot.com',
    measurementId: 'G-RYPW6D3ZRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUJKgwJNzCr-9dF8Cc6nLgbcAvBTHsF4A',
    appId: '1:719925176067:android:a0df22c4c5bc114b4b2b36',
    messagingSenderId: '719925176067',
    projectId: 'notificationtest-d8ce3',
    storageBucket: 'notificationtest-d8ce3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe4Tg2SBohgniQacw3-mqai4bAWMfz0wQ',
    appId: '1:719925176067:ios:f06675394424a0cb4b2b36',
    messagingSenderId: '719925176067',
    projectId: 'notificationtest-d8ce3',
    storageBucket: 'notificationtest-d8ce3.appspot.com',
    iosClientId: '719925176067-a89o2h00hqctekt77371sg0pm95tod2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasenotification',
  );
}
